language: python
sudo: false
python: 3.5
cache:
  pip: true
addons:
  apt:
    packages:
    - swig
    - libxml2-dev
    - libglpk-dev
    - glpk-utils
git:
  depth: 2000
env:
  matrix:
  - DEPLOY_BRANCH="gh-pages"
  global:
  - secure: clnt8G19fY/+BbKafTNe1G6vXTmbIN2PiODRF3z1oXG21RFR7JO6xrCBQOSq0zInDbNuVbaqVyeC0LAqpDl3uaWHPGnPPWU3CdXnPdqFkMDfml8zC3c4/4BYEKI55Q4NhJvML3rBdYOicpu95XxMbkksUX4J+ZE355YpyYbyWHPnvZYM88AoAcP0QI6lTI6BFhp3Nt1J2o/1vOq58syeQALTylsUE4Fu/HVMBNmOVo0ReySRveCrlhopMhzwOZ8X8nPlV5TO8rbX44ECt/ZhUrWEQszdJzKJ/59c1K2H55kymT8LtupvLDSOctB4upLDviHz5fIIUpoN7GGULggWu70L7piqiix5XzMNtF2xnl2UhxuM9d4i6+HKE5lP6YN8sIXHFmkp4vv9Dk4Xs3E6UJCZiYIj4ztN6S+bRc7r3g0n7AAmqRmDQI+FF/1Wpnhig/mD/xZ8tFVKkHMdaZpcNzNGHYC3aT9Yh7vLbhQcnODSlXhH8g6H82uOWuIKvCmP4Yy4znmrbNHdfRqUk31f27+sed7YcmDwkRQ0S43fsOBlfKEVNBbajmBDXe7NxJEwh1N5mdVxG0DQQuYsOPxdednbZXHTmW+9riH5mk8QfkLFOKT+LwCCHGuQe0Mpg9LL8Vk+KZnZKBB+cTyGf3DaUBdscKdnSIs5OjQfjhisvWQ=
  - secure: ADaZknI1BCIhRuh5jzzBPa2WL3nob9tRZ0cvYQPMrTBL949rOpsXn1kfsHjwdS/xj+bJBYHu7hnkJft0/adhckZj5SFPsxQV30Ty7q3Hjba5MXzM7cRIKpDBfTuOsdjPIBUbFx90NAvHf1QEcndAEjs2Nagd6ISEOTpgjSzO7DGzGerNchGAnU6OQL5tEjbB9nBQSedJ7n+K3tsdAFn+Xgut2At2/p9cJyQYZspLS4Ip7OiB3bprap9s8bhH2smkmQTotHKQNbeHGL5HdGPo8XVU984eyABmGEms1FlAYEipcvBBnOZwNTGUQ1LKMoEcXeu/fBkriNYbTnm8H6643gevNzcVZcovBIeKBpsaWa5Ei6WFskJCEHmpbSQrY0ozAu0R04Ephv4cvQKTzrLmcVI2Soy7J4guSKGcvd2QhPr2U5YalNbNS32ovaCaOKlofrxG440Smeh9FaQs6s5HfE20cVmR3RAjnmdMbw9uC4qSwnfCByl+xxqyflbbf4JRi2brD18H9B/WSyAyL9zWPD7AZrJkGKzZHHRwnyBNtgbKlHHgB1zbhYTnMbv4CB5Ia4cRnyvPeLVKgBa/gamj7V4WnFEMT6JSKhGxx83MX08seeToESCgBQwf5B7qrkzNRORFu3MlFdScQb9NUj5ZG917SOFBvDLPc2oMoSzUYKo=
before_install:
- travis_retry pip install -U pip setuptools wheel
install:
- travis_retry pip install -U -r requirements.in
script:
- git checkout master
- memote
after_script:
- scripts/deploy.sh
